### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by Revadike** [webmentordev/steam-auth-in-nuxt-3#1]
I could just spoof any steamid in the callback URL and it will still accept me.

**Comment by webmentordev** [comment]
I know the system is not secure because i just wanted to test the steam auth system. How the system works with redirects and getting user's info. it is a personal project as a hobby that's why never spent much time on it

**Comment by Revadike** [comment]
That's fine, just want to warn others that think of using this for their projects (which may need more security).

I can highly recommend https://github.com/DoctorMcKay/node-steam-signin, it has a simple API, and it's made by a trusted author.
